name: Beta

on:
    push:
        branches: [beta]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: "18.x"
            - run: npm ci
            - run: npm run build
            - run: echo beta.chrisbenti.com > ./build/CNAME
            - name: Pushes to another repository
              uses: cpina/github-action-push-to-another-repository@main
              env:
                  SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
              with:
                  source-directory: "build"
                  destination-github-username: "chrisbenti"
                  destination-repository-name: "beta.chrisbenti.com"
                  user-email: bot@chrisbenti.com
                  target-branch: main
