name: github pages

on:
    push:
        branches:
            - main # Set a branch name to trigger deployment

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
            - name: Install pnpm
              run: npm install -g pnpm
            - run: pnpm install --frozen-lockfile
            - run: pnpm prettier --check .
            - run: pnpm run spellcheck
            - run: pnpm run build

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./build
